version: "3"

services:
  app:
    build: ./app
    restart: always
    environment:
      - FLAG=SECCON{LE4RNING_FR0M_7HE_PA5T_FINDIN6_N0TABLE_VULNERABILITIE5}
  nginx:
    build: ./nginx
    restart: always
    # local
    ports:
      - "80:80"
      - "443:443"
    environment:
      - AUTH=off

    ## server (before contest starts)
    #ports:
    #  - "443:443"
    #environment:
    #  - "AUTH=closed site"

    ## server (after contest starts)
    #ports:
    #  - "443:443"
    #environment:
    #  - AUTH=off
